site_name: qianmoQ
site_url: https://qianmoq.com
site_author: qinamoQ
site_description: >-
  专注于技术分享的垂直博客,ClickHouse,Spring,Apache,Ambari,Presto

repo_name: qianmoq.com
repo_url: https://github.com/qianmoq/qianmoq.com

copyright: Copyright &copy; 2021 qianmoq.com

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - i18n:
      default_language: zh
      languages:
        zh: Chinese
      nav_translations:
        zh:
          home: 主页
          project: 项目
          configuration_common: common全局配置
          configuration_common_mysql: common全局配置(MySQL)
          configuration_common_hdfs: common全局配置(HDFS)
          configuration_node_broker: Broker节点配置部署
          configuration_node_coordinator: Coordinator节点配置部署
          configuration_node_historical: Historical节点配置部署
          configuration_node_middleManager: MiddleManager节点配置部署

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
#    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.indexes
    - content.tabs.link
    - content.code.annotate

nav:
  - 主页:
    - index.md
    - project: project.md
  - Apache Druid:
      - druid/index.md
      - Action:
          - Configuration(Common):
            - configuration_common: druid/action/configuration_common.md
            - configuration_common_mysql: druid/action/configuration_common_mysql.md
            - configuration_common_hdfs: druid/action/configuration_common_hdfs.md
          - Configuration(Node):
            - configuration_node_broker: druid/action/configuration_node_broker.md
            - configuration_node_coordinator: druid/action/configuration_node_coordinator.md
            - configuration_node_historical: druid/action/configuration_node_historical.md
            - configuration_node_middleManager: druid/action/configuration_node_middleManager.md
